services:
  - type: web
    name: match-django-api
    runtime: python
    repo: https://github.com/wusixuan0/jd-match-api
    plan: free
    region: ohio
    buildCommand: "./build.sh"
    startCommand: uvicorn config.asgi:application --host 0.0.0.0 --port $PORT
version: "1"