# Generated by Django 5.0.7 on 2024-08-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userfeedback_feedback_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
            ],
        ),
    ]
