# Generated by Django 5.0.7 on 2024-09-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_generatedresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytransaction',
            name='file_url',
            field=models.URLField(null=True),
        ),
    ]
