# Generated by Django 5.0.7 on 2024-09-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_temporarytransaction_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_url',
            field=models.URLField(null=True),
        ),
    ]
